sbin_PROGRAMS = tfkiss

tfkiss_SOURCES = \
    l2a.c \
    l2b.c \
    l2c.c \
    l2d.c \
    l2e.c \
    l2s.c \
    l2v.c \
    tfa.c \
    tfb.c \
    tfc.c \
    tfd.c \
    tfv.c \
    crc.c \
    init.c \
    main.c \
    process.c \
    routing.c

tfkiss_CFLAGS = -funsigned-char

noinst_HEADERS = \
    all.h \
    axip.h \
    init.h \
    kiss.h \
    l2.h \
    l2ext.h \
    l2s.h \
    tf.h \
    tfext.h \
    version.h
